const fs = require('fs');

const toolsToAdd = [
  // 1. Coding Practice & Interview Prep
  {
      "id": "leetcode",
      "name": "LeetCode",
      "description": "The world's leading online programming learning platform for interview prep.",
      "category": "Development",
      "url": "https://leetcode.com",
      "imageUrl": "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "leetcode.com",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "hackerrank",
      "name": "HackerRank",
      "description": "Practice coding, prepare for interviews, and get hired.",
      "category": "Development",
      "url": "https://hackerrank.com",
      "imageUrl": "https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "hackerrank.com",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "codeforces",
      "name": "Codeforces",
      "description": "Programming competitions and contests platform.",
      "category": "Development",
      "url": "https://codeforces.com",
      "imageUrl": "https://images.unsplash.com/photo-1526379095098-d400fd0bfce8?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "codeforces.com",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "codechef",
      "name": "CodeChef",
      "description": "A competitive programming community and educational initiative.",
      "category": "Development",
      "url": "https://codechef.com",
      "imageUrl": "https://images.unsplash.com/photo-1551033406-611cf9a28f67?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "codechef.com",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "atcoder",
      "name": "AtCoder",
      "description": "Programming contest site for anyone from beginners to experts.",
      "category": "Development",
      "url": "https://atcoder.jp",
      "imageUrl": "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "atcoder.jp",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "exercism",
      "name": "Exercism",
      "description": "Code practice and mentorship for everyone. Develop fluency in coding.",
      "category": "Development",
      "url": "https://exercism.org",
      "imageUrl": "https://images.unsplash.com/photo-1605379399642-870262d3d051?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "exercism.org",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "coderbyte",
      "name": "Coderbyte",
      "description": "The #1 platform for technical assessments and interview prep.",
      "category": "Development",
      "url": "https://coderbyte.com",
      "imageUrl": "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "coderbyte.com",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "project-euler",
      "name": "Project Euler",
      "description": "A series of challenging mathematical/computer programming problems.",
      "category": "Development",
      "url": "https://projecteuler.net",
      "imageUrl": "https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "projecteuler.net",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "sqlbolt",
      "name": "SQLBolt",
      "description": "Learn SQL with simple, interactive exercises.",
      "category": "Development",
      "url": "https://sqlbolt.com",
      "imageUrl": "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "sqlbolt.com",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "frontend-mentor",
      "name": "Frontend Mentor",
      "description": "Improve your front-end coding skills by building real projects.",
      "category": "Development",
      "url": "https://frontendmentor.io",
      "imageUrl": "https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "frontendmentor.io",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "roadmap-sh",
      "name": "Roadmap.sh",
      "description": "Community-driven roadmaps, articles, and resources for developers.",
      "category": "Development",
      "url": "https://roadmap.sh",
      "imageUrl": "https://images.unsplash.com/photo-1473221326025-9183b464c209?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "roadmap.sh",
      "brandColor": "var(--color-primary)"
  },

  // 2. Web Development & General Coding
  {
      "id": "freecodecamp",
      "name": "freeCodeCamp",
      "description": "Learn to code — for free. Build projects. Earn certifications.",
      "category": "Development",
      "url": "https://freecodecamp.org",
      "imageUrl": "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "freecodecamp.org",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "cs50",
      "name": "CS50",
      "description": "Harvard University's introduction to the intellectual enterprises of computer science and the art of programming.",
      "category": "Development",
      "url": "https://cs50.harvard.edu",
      "imageUrl": "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "cs50.harvard.edu",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "the-odin-project",
      "name": "The Odin Project",
      "description": "Your Career in Web Development Starts Here. Our full stack curriculum is free and supported by a passionate open source community.",
      "category": "Development",
      "url": "https://theodinproject.com",
      "imageUrl": "https://images.unsplash.com/photo-1504639725590-34d0984388bd?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "theodinproject.com",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "w3schools",
      "name": "W3Schools",
      "description": "The world's largest web developer site, with tutorials and references on web development languages.",
      "category": "Development",
      "url": "https://w3schools.com",
      "imageUrl": "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.6,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "w3schools.com",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "mdn",
      "name": "MDN Web Docs",
      "description": "The MDN Web Docs site provides information about Open Web technologies including HTML, CSS, and APIs for both Web sites and progressive web apps.",
      "category": "Development",
      "url": "https://developer.mozilla.org",
      "imageUrl": "https://images.unsplash.com/photo-1551033406-611cf9a28f67?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "developer.mozilla.org",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "geeksforgeeks",
      "name": "GeeksforGeeks",
      "description": "A computer science portal for geeks. It contains well written, well thought and well explained computer science and programming articles.",
      "category": "Development",
      "url": "https://geeksforgeeks.org",
      "imageUrl": "https://images.unsplash.com/photo-1526379095098-d400fd0bfce8?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "geeksforgeeks.org",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "codecademy",
      "name": "Codecademy",
      "description": "Learn the technical skills to get the job you want. Join over 50 million people choosing Codecademy to start a new career.",
      "category": "Development",
      "url": "https://codecademy.com",
      "imageUrl": "https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "codecademy.com",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "programiz",
      "name": "Programiz",
      "description": "Learn to code in Python, C/C++, Java, and other popular programming languages with our easy to follow tutorials, examples, online compiler and references.",
      "category": "Development",
      "url": "https://programiz.com",
      "imageUrl": "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "programiz.com",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "full-stack-open",
      "name": "Full Stack Open",
      "description": "Deep Dive Into Modern Web Development. Learn React, Redux, Node.js, MongoDB, GraphQL and TypeScript in one go!",
      "category": "Development",
      "url": "https://fullstackopen.com",
      "imageUrl": "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "fullstackopen.com",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "javatpoint",
      "name": "Javatpoint",
      "description": "Javatpoint provides tutorials and interview questions of all technology like java tutorial, android, java frameworks, javascript, ajax, core java, sql.",
      "category": "Development",
      "url": "https://javatpoint.com",
      "imageUrl": "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.6,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "javatpoint.com",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "devdocs",
      "name": "DevDocs",
      "description": "DevDocs combines multiple API documentations in a fast, organized, and searchable interface.",
      "category": "Development",
      "url": "https://devdocs.io",
      "imageUrl": "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "devdocs.io",
      "brandColor": "var(--color-primary)"
  },

  // 3. AI, Data Science & Machine Learning
  {
      "id": "kaggle",
      "name": "Kaggle Learn",
      "description": "Gain the skills you need to do independent data science projects. We pare down complex topics to their key practical components.",
      "category": "Development",
      "url": "https://kaggle.com/learn",
      "imageUrl": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "kaggle.com",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "google-ai",
      "name": "Google AI",
      "description": "Explore Google's open source machine learning and AI technology, research, and tools.",
      "category": "Development",
      "url": "https://ai.google",
      "imageUrl": "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "ai.google",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "deeplearning-ai",
      "name": "DeepLearning.AI",
      "description": "Learn from the AI pioneer Andrew Ng and a world-class team of experts. Master AI through courses, specializations, and certificates.",
      "category": "Development",
      "url": "https://deeplearning.ai",
      "imageUrl": "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=800",
      "pricing": "Paid",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "deeplearning.ai",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "fast-ai",
      "name": "Fast.ai",
      "description": "Making neural nets uncool again. Fast.ai is a non-profit research group focused on deep learning and artificial intelligence.",
      "category": "Development",
      "url": "https://fast.ai",
      "imageUrl": "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "fast.ai",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "hugging-face-course",
      "name": "Hugging Face Course",
      "description": "This course will teach you about natural language processing (NLP) using libraries from the Hugging Face ecosystem.",
      "category": "Development",
      "url": "https://huggingface.co/course",
      "imageUrl": "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "huggingface.co",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "microsoft-learn-ai",
      "name": "Microsoft Learn AI",
      "description": "Discover how Microsoft AI and machine learning products can help you build intelligent apps and solutions.",
      "category": "Development",
      "url": "https://learn.microsoft.com/en-us/training/paths/get-started-with-artificial-intelligence-on-azure/",
      "imageUrl": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "learn.microsoft.com",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "openai-cookbook",
      "name": "OpenAI Cookbook",
      "description": "The OpenAI Cookbook shares example code and prompts for accomplishing common tasks with the OpenAI API.",
      "category": "Development",
      "url": "https://cookbook.openai.com",
      "imageUrl": "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "cookbook.openai.com",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "datacamp",
      "name": "DataCamp",
      "description": "Learn the data and AI skills you need online at your own pace—from non-coding essentials to data science and machine learning.",
      "category": "Development",
      "url": "https://datacamp.com",
      "imageUrl": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "datacamp.com",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "ibm-skillsbuild",
      "name": "IBM SkillsBuild",
      "description": "Free digital learning on tech, workplace skills, and more. Get badges to boost your career.",
      "category": "Development",
      "url": "https://skillsbuild.org",
      "imageUrl": "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "skillsbuild.org",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "sifu-yik",
      "name": "Sifu Yik",
      "description": "Learn AI and Data Science from experts.",
      "category": "Development",
      "url": "https://sifuyik.com",
      "imageUrl": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.6,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "sifuyik.com",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "tensorflow-tutorials",
      "name": "TensorFlow Tutorials",
      "description": "Learn how to use TensorFlow with these comprehensive tutorials for all skill levels.",
      "category": "Development",
      "url": "https://tensorflow.org/tutorials",
      "imageUrl": "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "tensorflow.org",
      "brandColor": "var(--color-primary)"
  }
];

const fsPath = 'data/tools.ts';
let content = fs.readFileSync(fsPath, 'utf8');

// Find the end of the array
const arrayEndIndex = content.lastIndexOf('];');
if (arrayEndIndex !== -1) {
    const stringToAdd = toolsToAdd.map(tool => JSON.stringify(tool, null, 4)).join(',\n') + ',\n';
    
    // Insert before the closing bracket
    const newContent = content.slice(0, arrayEndIndex) + ',\n' + stringToAdd + content.slice(arrayEndIndex);
    fs.writeFileSync(fsPath, newContent);
    console.log(`Added ${toolsToAdd.length} tools to tools.ts`);
} else {
    console.error("Could not find the end of the MOCK_TOOLS array.");
}

