const fs = require('fs');
const filePath = 'data/tools.ts';
let content = fs.readFileSync(filePath, 'utf8');

const googleTools = [
  {
      "id": "google-search-console",
      "name": "Google Search Console",
      "description": "Measure your site's search traffic and performance, fix issues, and make your site shine in Google Search results.",
      "category": "Official Google Tools",
      "url": "https://search.google.com/search-console",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": true,
      "dateAdded": new Date().toISOString(),
      "domain": "search.google.com",
      "brandColor": "#4285F4",
      "tags": ["SEO", "Organic Growth"]
  },
  {
      "id": "google-trends",
      "name": "Google Trends",
      "description": "Explore how Google data can be used to tell stories. Analyze search volume and trends globally.",
      "category": "Official Google Tools",
      "url": "https://trends.google.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "trends.google.com",
      "brandColor": "#4285F4",
      "tags": ["SEO", "Organic Growth"]
  },
  {
      "id": "google-keyword-planner",
      "name": "Google Keyword Planner",
      "description": "Find the right keywords to target for display ads, search ads, video ads, and app ads.",
      "category": "Official Google Tools",
      "url": "https://ads.google.com/home/tools/keyword-planner/",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "ads.google.com",
      "brandColor": "#4285F4",
      "tags": ["SEO", "Organic Growth"]
  },
  {
      "id": "google-business-profile",
      "name": "Google Business Profile",
      "description": "Manage your online presence across Google, including Search and Maps, to reach local customers.",
      "category": "Official Google Tools",
      "url": "https://business.google.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "business.google.com",
      "brandColor": "#4285F4",
      "tags": ["SEO", "Organic Growth"]
  },
  {
      "id": "google-alerts",
      "name": "Google Alerts",
      "description": "Monitor the web for interesting new content based on your custom search queries.",
      "category": "Official Google Tools",
      "url": "https://www.google.com/alerts",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.6,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "google.com",
      "brandColor": "#4285F4",
      "tags": ["SEO", "Organic Growth"]
  },
  {
      "id": "google-analytics-4",
      "name": "Google Analytics 4 (GA4)",
      "description": "Measure your advertising ROI as well as track your Flash, video, and social networking sites and applications.",
      "category": "Official Google Tools",
      "url": "https://analytics.google.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.9,
      "featured": true,
      "dateAdded": new Date().toISOString(),
      "domain": "analytics.google.com",
      "brandColor": "#F4B400",
      "tags": ["Analytics", "Tracking"]
  },
  {
      "id": "google-tag-manager",
      "name": "Google Tag Manager",
      "description": "Manage all your website tags without editing code. Simple, reliable, easily integrated tag management solutions.",
      "category": "Official Google Tools",
      "url": "https://tagmanager.google.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "tagmanager.google.com",
      "brandColor": "#4285F4",
      "tags": ["Analytics", "Tracking"]
  },
  {
      "id": "looker-studio",
      "name": "Looker Studio",
      "description": "Unlock the power of your data with interactive dashboards and engaging reports that inspire smarter business decisions.",
      "category": "Official Google Tools",
      "url": "https://lookerstudio.google.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "lookerstudio.google.com",
      "brandColor": "#4285F4",
      "tags": ["Analytics", "Tracking"]
  },
  {
      "id": "campaign-url-builder",
      "name": "Campaign URL Builder",
      "description": "Easily add campaign parameters to URLs so you can track Custom Campaigns in Google Analytics.",
      "category": "Official Google Tools",
      "url": "https://ga-dev-tools.google/campaign-url-builder/",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "ga-dev-tools.google",
      "brandColor": "#4285F4",
      "tags": ["Analytics", "Tracking"]
  },
  {
      "id": "google-analytics-demo",
      "name": "Google Analytics Demo Account",
      "description": "Access the Google Analytics demo account to experiment with real business data.",
      "category": "Official Google Tools",
      "url": "https://support.google.com/analytics/answer/6367342",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.6,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "support.google.com",
      "brandColor": "#F4B400",
      "tags": ["Analytics", "Tracking"]
  },
  {
      "id": "google-ads",
      "name": "Google Ads",
      "description": "Get in front of customers when they're searching for businesses like yours on Google Search and Maps.",
      "category": "Official Google Tools",
      "url": "https://ads.google.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Usage Based",
      "rating": 4.8,
      "featured": true,
      "dateAdded": new Date().toISOString(),
      "domain": "ads.google.com",
      "brandColor": "#4285F4",
      "tags": ["Paid Marketing"]
  },
  {
      "id": "google-ads-editor",
      "name": "Google Ads Editor",
      "description": "Download your campaigns to make bulk changes offline, then upload them directly to Google Ads.",
      "category": "Official Google Tools",
      "url": "https://ads.google.com/home/tools/ads-editor/",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "ads.google.com",
      "brandColor": "#4285F4",
      "tags": ["Paid Marketing"]
  },
  {
      "id": "performance-planner",
      "name": "Performance Planner",
      "description": "Create plans for your advertising spend and see how changes to campaigns might affect key metrics.",
      "category": "Official Google Tools",
      "url": "https://support.google.com/google-ads/answer/94228",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.6,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "support.google.com",
      "brandColor": "#4285F4",
      "tags": ["Paid Marketing"]
  },
  {
      "id": "google-merchant-center",
      "name": "Google Merchant Center",
      "description": "Upload your store and product data to Google and make it available for Shopping ads and other Google services.",
      "category": "Official Google Tools",
      "url": "https://merchants.google.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "merchants.google.com",
      "brandColor": "#4285F4",
      "tags": ["Paid Marketing"]
  },
  {
      "id": "ads-transparency-center",
      "name": "Ads Transparency Center",
      "description": "A searchable hub of verified advertisers and all the ads they are running across Google's platforms.",
      "category": "Official Google Tools",
      "url": "https://adstransparency.google.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.5,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "adstransparency.google.com",
      "brandColor": "#4285F4",
      "tags": ["Paid Marketing"]
  },
  {
      "id": "google-gemini",
      "name": "Google Gemini",
      "description": "Google's most capable AI model yet. Built to be multimodal from the ground up.",
      "category": "Official Google Tools",
      "url": "https://gemini.google.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.9,
      "featured": true,
      "dateAdded": new Date().toISOString(),
      "domain": "gemini.google.com",
      "brandColor": "#0F9D58",
      "tags": ["AI", "Productivity"]
  },
  {
      "id": "notebooklm",
      "name": "NotebookLM",
      "description": "An AI-first notebook, grounded in your own documents, to help you gain insights and synthesize information.",
      "category": "Official Google Tools",
      "url": "https://notebooklm.google.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.8,
      "featured": true,
      "dateAdded": new Date().toISOString(),
      "domain": "notebooklm.google.com",
      "brandColor": "#0F9D58",
      "tags": ["AI", "Productivity"]
  },
  {
      "id": "google-ai-studio",
      "name": "Google AI Studio",
      "description": "The fastest way to start building with Gemini. Prototype and launch generative AI applications.",
      "category": "Official Google Tools",
      "url": "https://aistudio.google.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.9,
      "featured": true,
      "dateAdded": new Date().toISOString(),
      "domain": "aistudio.google.com",
      "brandColor": "#0F9D58",
      "tags": ["AI", "Productivity"]
  },
  {
      "id": "google-vids",
      "name": "Google Vids",
      "description": "An AI-powered video creation app for Google Workspace, designed to help you create compelling video presentations.",
      "category": "Official Google Tools",
      "url": "https://workspace.google.com/products/vids/",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Paid",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "workspace.google.com",
      "brandColor": "#4285F4",
      "tags": ["AI", "Productivity"]
  },
  {
      "id": "google-workspace",
      "name": "Google Workspace",
      "description": "Seamlessly integrates messaging, meetings, docs, and tasks—all built with trusted Google security and AI.",
      "category": "Official Google Tools",
      "url": "https://workspace.google.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Paid",
      "rating": 4.9,
      "featured": true,
      "dateAdded": new Date().toISOString(),
      "domain": "workspace.google.com",
      "brandColor": "#4285F4",
      "tags": ["Productivity"]
  },
  {
      "id": "think-with-google",
      "name": "Think with Google",
      "description": "Uncover marketing insights, research, and trends to stay ahead of the curve and grow your business.",
      "category": "Official Google Tools",
      "url": "https://www.thinkwithgoogle.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "thinkwithgoogle.com",
      "brandColor": "#4285F4",
      "tags": ["Marketing Resources"]
  },
  {
      "id": "grow-with-google",
      "name": "Grow with Google",
      "description": "Free training, tools, and events to help you grow your skills, career, or business.",
      "category": "Official Google Tools",
      "url": "https://grow.google",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "grow.google",
      "brandColor": "#4285F4",
      "tags": ["Marketing Resources"]
  },
  {
      "id": "google-fonts",
      "name": "Google Fonts",
      "description": "Making the web more beautiful, fast, and open through great typography and iconography.",
      "category": "Official Google Tools",
      "url": "https://fonts.google.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": true,
      "dateAdded": new Date().toISOString(),
      "domain": "fonts.google.com",
      "brandColor": "#4285F4",
      "tags": ["Marketing Resources"]
  },
  {
      "id": "google-sites",
      "name": "Google Sites",
      "description": "Effortlessly create impactful team sites. No programming or design skills required.",
      "category": "Official Google Tools",
      "url": "https://sites.google.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.5,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "sites.google.com",
      "brandColor": "#4285F4",
      "tags": ["Marketing Resources"]
  },
  {
      "id": "google-maps-platform",
      "name": "Google Maps Platform",
      "description": "Build custom, agile experiences that bring the real world to your users with static and dynamic maps, Street View imagery, and 360° views.",
      "category": "Official Google Tools",
      "url": "https://mapsplatform.google.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Usage Based",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "mapsplatform.google.com",
      "brandColor": "#34A853",
      "tags": ["Marketing Resources", "Development"]
  }
];

if (!content.includes('google-search-console')) {
  // insert after export const MOCK_TOOLS: Tool[] = [
  const replacement = 'export const MOCK_TOOLS: Tool[] = [\n' + googleTools.map(t => JSON.stringify(t, null, 4)).join(',\n') + ',';
  content = content.replace('export const MOCK_TOOLS: Tool[] = [', replacement);
  fs.writeFileSync(filePath, content);
  console.log('Added Google Tools');
} else {
  console.log('Google Tools already added');
}
