const fs = require('fs');

const toolsToAdd = [
  // 6. Business, Marketing & Career
  {
      "id": "hubspot-academy",
      "name": "HubSpot Academy",
      "description": "Free online training for inbound marketing, sales, and customer service professionals.",
      "category": "Marketing & SEO",
      "url": "https://academy.hubspot.com",
      "imageUrl": "https://images.unsplash.com/photo-1552581234-26160f608093?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "academy.hubspot.com",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "google-digital-garage",
      "name": "Google Digital Garage",
      "description": "Discover a range of free learning content designed to help your business or in your career.",
      "category": "Marketing & SEO",
      "url": "https://learndigital.withgoogle.com/digitalgarage",
      "imageUrl": "https://images.unsplash.com/photo-1573164713988-8665fc963095?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "learndigital.withgoogle.com",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "meta-blueprint",
      "name": "Meta Blueprint",
      "description": "Free online training for advertising on Facebook, Instagram, Messenger and WhatsApp.",
      "category": "Marketing & SEO",
      "url": "https://www.facebook.com/business/learn",
      "imageUrl": "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "facebook.com",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "semrush-academy",
      "name": "Semrush Academy",
      "description": "Free SEO and digital marketing courses from top industry experts.",
      "category": "Marketing & SEO",
      "url": "https://www.semrush.com/academy/",
      "imageUrl": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "semrush.com",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "ahrefs-academy",
      "name": "Ahrefs Academy",
      "description": "Actionable SEO tutorials and marketing courses from Ahrefs.",
      "category": "Marketing & SEO",
      "url": "https://ahrefs.com/academy",
      "imageUrl": "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "ahrefs.com",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "coursera",
      "name": "Coursera",
      "description": "Build skills with courses, certificates, and degrees online from world-class universities and companies.",
      "category": "Education",
      "url": "https://www.coursera.org",
      "imageUrl": "https://images.unsplash.com/photo-1501504905252-473c47e087f8?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "coursera.org",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "edx",
      "name": "edX",
      "description": "Access 2500+ Online Courses from 140 Top Institutions.",
      "category": "Education",
      "url": "https://www.edx.org",
      "imageUrl": "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "edx.org",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "alison",
      "name": "Alison",
      "description": "Free Online Courses With Certificates & Diplomas.",
      "category": "Education",
      "url": "https://alison.com",
      "imageUrl": "https://images.unsplash.com/photo-1546410531-ee4cb47b5315?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "alison.com",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "futurelearn",
      "name": "FutureLearn",
      "description": "Online Courses and Degrees from Top Universities.",
      "category": "Education",
      "url": "https://www.futurelearn.com",
      "imageUrl": "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "futurelearn.com",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "openlearn",
      "name": "OpenLearn",
      "description": "Free learning from The Open University.",
      "category": "Education",
      "url": "https://www.open.edu/openlearn",
      "imageUrl": "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "open.edu",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "skillshop",
      "name": "Skillshop (Google)",
      "description": "Develop skills you can apply right away, with e-learning courses designed by Google product experts.",
      "category": "Marketing & SEO",
      "url": "https://skillshop.exceedlms.com",
      "imageUrl": "https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "skillshop.exceedlms.com",
      "brandColor": "var(--color-primary)"
  },

  // 7. Mathematics & Science
  {
      "id": "khan-academy",
      "name": "Khan Academy",
      "description": "Free online courses, lessons and practice. You can learn anything.",
      "category": "Education",
      "url": "https://www.khanacademy.org",
      "imageUrl": "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "khanacademy.org",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "brilliant",
      "name": "Brilliant",
      "description": "Build quantitative skills in math, science, and computer science with interactive lessons.",
      "category": "Education",
      "url": "https://brilliant.org",
      "imageUrl": "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "brilliant.org",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "pauls-online-math-notes",
      "name": "Paul's Online Math Notes",
      "description": "Free math notes and tutorials from Paul Dawkins at Lamar University.",
      "category": "Education",
      "url": "https://tutorial.math.lamar.edu",
      "imageUrl": "https://images.unsplash.com/photo-1632516643771-69e1358c97dd?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "tutorial.math.lamar.edu",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "mit-opencourseware",
      "name": "MIT OpenCourseWare",
      "description": "Free lecture notes, exams, and videos from MIT. No registration required.",
      "category": "Education",
      "url": "https://ocw.mit.edu",
      "imageUrl": "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "ocw.mit.edu",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "ck-12",
      "name": "CK-12",
      "description": "Free, customizable, interactive online textbooks, practice, and more.",
      "category": "Education",
      "url": "https://www.ck12.org",
      "imageUrl": "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "ck12.org",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "nasa-stem",
      "name": "NASA STEM",
      "description": "NASA's STEM engagement site for students and educators.",
      "category": "Education",
      "url": "https://www.nasa.gov/stem",
      "imageUrl": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "nasa.gov",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "phet-simulations",
      "name": "PhET Simulations",
      "description": "Free interactive math and science simulations from the University of Colorado Boulder.",
      "category": "Education",
      "url": "https://phet.colorado.edu",
      "imageUrl": "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "phet.colorado.edu",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "wolfram-demonstrations",
      "name": "Wolfram Demonstrations Project",
      "description": "Open-code interactive simulations of concepts in science, math, technology, and more.",
      "category": "Education",
      "url": "https://demonstrations.wolfram.com",
      "imageUrl": "https://images.unsplash.com/photo-1632516643771-69e1358c97dd?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "demonstrations.wolfram.com",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "openstax",
      "name": "OpenStax",
      "description": "Free, peer-reviewed, openly licensed textbooks.",
      "category": "Education",
      "url": "https://openstax.org",
      "imageUrl": "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "openstax.org",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "nptel",
      "name": "NPTEL",
      "description": "National Programme on Technology Enhanced Learning (NPTEL) offers online courses and certification.",
      "category": "Education",
      "url": "https://nptel.ac.in",
      "imageUrl": "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "nptel.ac.in",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "byjus-free-resources",
      "name": "BYJU'S Free Resources",
      "description": "Free educational resources and video lessons.",
      "category": "Education",
      "url": "https://byjus.com",
      "imageUrl": "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "byjus.com",
      "brandColor": "var(--color-primary)"
  },

  // 8. Productivity & Everything Else
  {
      "id": "notion-academy",
      "name": "Notion Academy",
      "description": "Learn how to use Notion with courses, tutorials, and guides.",
      "category": "Productivity",
      "url": "https://www.notion.so/help/notion-academy",
      "imageUrl": "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "notion.so",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "obsidian-help",
      "name": "Obsidian Help",
      "description": "Documentation for Obsidian, a powerful knowledge base on top of a local folder of plain text Markdown files.",
      "category": "Productivity",
      "url": "https://help.obsidian.md",
      "imageUrl": "https://images.unsplash.com/photo-1522881113591-5452277d7045?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "help.obsidian.md",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "overthewire",
      "name": "OverTheWire",
      "description": "Wargames to help you learn and practice security concepts in the form of fun-filled games.",
      "category": "Development",
      "url": "https://overthewire.org/wargames/",
      "imageUrl": "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "overthewire.org",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "mozilla-observatory",
      "name": "Mozilla Observatory",
      "description": "A set of tools to analyze your website and let you know if it is secure.",
      "category": "Development",
      "url": "https://observatory.mozilla.org",
      "imageUrl": "https://images.unsplash.com/photo-1510915228340-29c85a43dcfe?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "observatory.mozilla.org",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "internet-archive",
      "name": "Internet Archive",
      "description": "Non-profit library of millions of free books, movies, software, music, websites, and more.",
      "category": "Education",
      "url": "https://archive.org",
      "imageUrl": "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "archive.org",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "open-library",
      "name": "Open Library",
      "description": "An open, editable library catalog, building towards a web page for every book ever published.",
      "category": "Education",
      "url": "https://openlibrary.org",
      "imageUrl": "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "openlibrary.org",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "iep",
      "name": "Internet Encyclopedia of Philosophy",
      "description": "A peer-reviewed academic resource.",
      "category": "Education",
      "url": "https://iep.utm.edu",
      "imageUrl": "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&q=80&w=800",
      "pricing": "Free",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "iep.utm.edu",
      "brandColor": "var(--color-primary)"
  },
  {
      "id": "youtube",
      "name": "YouTube",
      "description": "Enjoy the videos and music you love, upload original content, and share it all with friends, family, and the world on YouTube.",
      "category": "Social Media",
      "url": "https://youtube.com",
      "imageUrl": "https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.9,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "youtube.com",
      "brandColor": "var(--color-primary)"
  }
];

const fsPath = 'data/tools.ts';
let content = fs.readFileSync(fsPath, 'utf8');

// Find the end of the array
const arrayEndIndex = content.lastIndexOf('];');
if (arrayEndIndex !== -1) {
    const stringToAdd = toolsToAdd.map(tool => JSON.stringify(tool, null, 4)).join(',\n') + ',\n';
    
    // Insert before the closing bracket
    const newContent = content.slice(0, arrayEndIndex) + ',\n' + stringToAdd + content.slice(arrayEndIndex);
    fs.writeFileSync(fsPath, newContent);
    console.log(`Added ${toolsToAdd.length} tools to tools.ts`);
} else {
    console.error("Could not find the end of the MOCK_TOOLS array.");
}

