import fs from 'fs';

const constantsContent = fs.readFileSync('constants.tsx', 'utf8');

const toolsToCheck = [
  { name: 'SurgeGraph', category: 'SEO' },
  { name: 'HoppyCopy', category: 'Writing' },
  { name: 'Sudowrite', category: 'Writing' },
  { name: 'Paperpal', category: 'Writing' },
  { name: 'Squibler', category: 'Writing' },
  { name: 'n8n', category: 'Productivity' },
  { name: 'Manus', category: 'Productivity' },
  { name: 'Make', category: 'Productivity' },
  { name: 'Zapier', category: 'Productivity' },
  { name: 'AutoGPT', category: 'Chatbots' },
  { name: 'Cursor', category: 'Coding' },
  { name: 'Replit', category: 'Coding' },
  { name: 'v0', category: 'Coding' },
  { name: 'Windsurf', category: 'Coding' },
  { name: 'Copilot', category: 'Coding' },
  { name: 'Bubble', category: 'No-Code' },
  { name: 'Lovable', category: 'Design' },
  { name: 'Bolt', category: 'Coding' },
  { name: 'Dyad', category: 'Design' },
  { name: 'GPTZero', category: 'Research' },
  { name: 'ZeroGPT', category: 'Research' },
  { name: 'Originality', category: 'Research' },
  { name: 'Copyleaks', category: 'Research' },
  { name: 'ahrefs', category: 'SEO' },
  { name: 'Semrush', category: 'SEO' },
  { name: 'Moz', category: 'SEO' },
  { name: 'RankMath', category: 'SEO' },
  { name: 'Veo', category: 'Video' },
  { name: 'Hailuo', category: 'Video' },
  { name: 'Synthesia', category: 'Video' },
  { name: 'RunwayML', category: 'Video' },
  { name: 'Filmora', category: 'Video' },
  { name: 'ElevenLabs', category: 'Voice' },
  { name: 'Suno', category: 'Music' },
  { name: 'Speechefy', category: 'Voice' },
  { name: 'Murf AI', category: 'Voice' },
  { name: 'Amper Music', category: 'Music' },
  { name: 'Grok', category: 'Chatbots' },
  { name: 'Ideogram', category: 'Image' },
  { name: 'Midjourney', category: 'Image' },
  { name: 'Gemini', category: 'Chatbots' },
  { name: 'Canva', category: 'Design' },
  { name: 'Beautiful.AI', category: 'Productivity' },
  { name: 'Gamma', category: 'Productivity' },
  { name: 'Pitch', category: 'Productivity' },
  { name: 'Plus', category: 'Productivity' },
  { name: 'PopAi', category: 'Productivity' },
  { name: 'Presentation.AI', category: 'Productivity' },
  { name: 'Slidesgo', category: 'Productivity' },
  { name: 'Tome', category: 'Productivity' },
  { name: 'ChatGPT', category: 'Chatbots' },
  { name: 'Claude', category: 'Chatbots' },
  { name: 'DeepSeek', category: 'Chatbots' },
  { name: 'Meta AI', category: 'Chatbots' },
  { name: 'MS Copilot', category: 'Chatbots' },
  { name: 'Perplexity', category: 'Research' },
  { name: 'Bricks', category: 'Data' },
  { name: 'Formula Bot', category: 'Data' },
  { name: 'Gigasheet', category: 'Data' },
  { name: 'Rows AI', category: 'Data' },
  { name: 'SheetAI', category: 'Data' },
  { name: 'Calendly', category: 'Productivity' },
  { name: 'Clockwise', category: 'Productivity' },
  { name: 'Motion', category: 'Productivity' },
  { name: 'Reclaim AI', category: 'Productivity' },
  { name: 'Taskade', category: 'Productivity' },
  { name: 'Trevor AI', category: 'Productivity' },
  { name: 'Mem', category: 'Productivity' },
  { name: 'Notion', category: 'Productivity' },
  { name: 'Tettra', category: 'Productivity' },
  { name: 'Adobe', category: 'Image' },
  { name: 'DALL-E', category: 'Image' },
  { name: 'FLUX.1', category: 'Image' },
  { name: 'Recraft', category: 'Image' },
  { name: 'Stable Diffusion', category: 'Image' },
  { name: 'Copy.ai', category: 'Writing' },
  { name: 'Grammerly', category: 'Writing' },
  { name: 'Jasper', category: 'Writing' },
  { name: 'JotBot', category: 'Writing' },
  { name: 'Quarkle', category: 'Writing' },
  { name: 'Quillbot', category: 'Writing' },
  { name: 'Rytr', category: 'Writing' },
  { name: 'Writesonic', category: 'Writing' },
  { name: 'Clippit.Ai', category: 'Productivity' },
  { name: 'Friday', category: 'Productivity' },
  { name: 'Mailmaestro', category: 'Productivity' },
  { name: 'Shortwave', category: 'Productivity' },
  { name: 'Superhuman', category: 'Productivity' },
  { name: 'Integrately', category: 'Productivity' },
  { name: 'Monday.com', category: 'Productivity' },
  { name: 'Wrike', category: 'Productivity' },
  { name: 'AutoDraw', category: 'Design' },
  { name: 'Design.com', category: 'Design' },
  { name: 'Framer', category: 'Design' },
  { name: 'Microsoft Designer', category: 'Design' },
  { name: 'Uizard', category: 'Design' },
  { name: 'Deckpilot', category: 'Data' },
  { name: 'Flourish', category: 'Data' },
  { name: 'Julius', category: 'Data' },
  { name: 'Visme', category: 'Data' },
  { name: 'Zing Data', category: 'Data' },
  { name: 'Askcodi', category: 'Coding' },
  { name: 'Codiga', category: 'Coding' },
  { name: 'GitHub Copilot', category: 'Coding' },
  { name: 'Qodo', category: 'Coding' },
  { name: 'Tabnine', category: 'Coding' },
  { name: 'Avoma', category: 'Productivity' },
  { name: 'Equal Time', category: 'Productivity' },
  { name: 'Fathom', category: 'Productivity' },
  { name: 'Fellow.app', category: 'Productivity' },
  { name: 'Fireflies', category: 'Productivity' },
  { name: 'Krisp', category: 'Productivity' },
  { name: 'Otter', category: 'Productivity' },
  { name: 'Descript', category: 'Video' },
  { name: 'Haiper AI', category: 'Video' },
  { name: 'Invideo AI', category: 'Video' },
  { name: 'Kling', category: 'Video' },
  { name: 'Krea AI', category: 'Video' },
  { name: 'LTX Studio', category: 'Video' },
  { name: 'Luma AI', category: 'Video' },
  { name: 'Pika AI', category: 'Video' },
  { name: 'Runway', category: 'Video' },
  { name: 'Sora', category: 'Video' }
];

const missingTools = [];
let nextId = 423; // from the last ID in constants.tsx

for (const tool of toolsToCheck) {
  const regex = new RegExp(`name:\\s*['"]${tool.name}['"]`, 'i');
  if (!regex.test(constantsContent)) {
    missingTools.push({
      id: String(nextId++),
      name: tool.name,
      description: `Powerful AI tool for ${tool.category}.`,
      category: tool.category,
      url: `https://www.google.com/search?q=${tool.name}+AI`,
      imageUrl: `https://picsum.photos/400/200?random=${nextId}`,
      pricing: 'Freemium',
      rating: 4.5,
      featured: false,
      dateAdded: new Date().toISOString().split('T')[0],
      tags: [tool.category, 'AI', 'Tool']
    });
  }
}

let newToolsString = missingTools.map(t => `  {
    id: '${t.id}',
    name: '${t.name}',
    description: '${t.description}',
    category: '${t.category}',
    url: '${t.url}',
    imageUrl: '${t.imageUrl}',
    pricing: '${t.pricing}',
    rating: ${t.rating},
    featured: ${t.featured},
    dateAdded: '${t.dateAdded}',
    tags: ${JSON.stringify(t.tags)}
  }`).join(',\n');

if (newToolsString) {
  const updatedContent = constantsContent.replace(/];\s*$/, `,\n${newToolsString}\n];\n`);
  fs.writeFileSync('constants.tsx', updatedContent);
  console.log(`Added ${missingTools.length} missing tools.`);
} else {
  console.log('No missing tools found.');
}
