const fs = require('fs');
const filePath = 'data/tools.ts';
let content = fs.readFileSync(filePath, 'utf8');

const newTools = [
  // Social Media Automation
  {
      "id": "manychat-automation",
      "name": "ManyChat",
      "description": "Automate interactive conversations in Instagram Direct Messages, Facebook Messenger, and SMS to grow your brand.",
      "category": "Social Media Automation",
      "url": "https://manychat.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "manychat.com",
      "brandColor": "#0084FF"
  },
  {
      "id": "metricool-automation",
      "name": "Metricool",
      "description": "The Swiss army knife for social media professionals. Analyze, manage, and grow your digital presence.",
      "category": "Social Media Automation",
      "url": "https://metricool.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "metricool.com",
      "brandColor": "#FF5252"
  },
  {
      "id": "buffer-automation",
      "name": "Buffer",
      "description": "The most intuitive, affordable, and authentic way to reach more people on social media.",
      "category": "Social Media Automation",
      "url": "https://buffer.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.6,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "buffer.com",
      "brandColor": "#2C4BFF"
  },
  {
      "id": "publer-automation",
      "name": "Publer",
      "description": "Collaborate, schedule & analyze your posts for Facebook, Instagram, TikTok, Twitter, LinkedIn, Pinterest, Google Business, YouTube.",
      "category": "Social Media Automation",
      "url": "https://publer.io",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "publer.io",
      "brandColor": "#08A05C"
  },
  {
      "id": "socialbee-automation",
      "name": "SocialBee",
      "description": "Social media management tool for businesses, agencies, and entrepreneurs. Create, schedule, and post.",
      "category": "Social Media Automation",
      "url": "https://socialbee.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Paid",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "socialbee.com",
      "brandColor": "#FFD200"
  },

  // Workflow Automation
  {
      "id": "zapier-automation",
      "name": "Zapier",
      "description": "Connect your apps and automate workflows. Easy automation for busy people.",
      "category": "Workflow Automation",
      "url": "https://zapier.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.8,
      "featured": true,
      "dateAdded": new Date().toISOString(),
      "domain": "zapier.com",
      "brandColor": "#FF4A00"
  },
  {
      "id": "make-automation",
      "name": "Make",
      "description": "Make allows you to visually create, build and automate workflows. Unbounded possibilities.",
      "category": "Workflow Automation",
      "url": "https://make.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.9,
      "featured": true,
      "dateAdded": new Date().toISOString(),
      "domain": "make.com",
      "brandColor": "#7B1FA2"
  },
  {
      "id": "n8n-automation",
      "name": "n8n",
      "description": "Free and open node-based Workflow Automation Tool. Easily automate tasks across different services.",
      "category": "Workflow Automation",
      "url": "https://n8n.io",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "n8n.io",
      "brandColor": "#FF6D5A"
  },
  {
      "id": "pabbly-connect-automation",
      "name": "Pabbly Connect",
      "description": "Automate all your integrations and tasks. Best alternative to Zapier.",
      "category": "Workflow Automation",
      "url": "https://pabbly.com/connect",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Paid",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "pabbly.com",
      "brandColor": "#1A73E8"
  },
  {
      "id": "ifttt-automation",
      "name": "IFTTT",
      "description": "Get all your apps and devices talking to each other. Do more with the services you love.",
      "category": "Workflow Automation",
      "url": "https://ifttt.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.6,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "ifttt.com",
      "brandColor": "#000000"
  },

  // Email Automation
  {
      "id": "mailchimp-automation",
      "name": "Mailchimp",
      "description": "Marketing automation platform and email marketing service for businesses.",
      "category": "Email Automation",
      "url": "https://mailchimp.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.6,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "mailchimp.com",
      "brandColor": "#FFE01B"
  },
  {
      "id": "brevo-automation",
      "name": "Brevo",
      "description": "Send email, SMS, and WhatsApp campaigns. Marketing automation platform.",
      "category": "Email Automation",
      "url": "https://brevo.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "brevo.com",
      "brandColor": "#0092FF"
  },
  {
      "id": "activecampaign-automation",
      "name": "ActiveCampaign",
      "description": "Customer Experience Automation platform combining email marketing, marketing automation, CRM.",
      "category": "Email Automation",
      "url": "https://activecampaign.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Paid",
      "rating": 4.8,
      "featured": true,
      "dateAdded": new Date().toISOString(),
      "domain": "activecampaign.com",
      "brandColor": "#356AE6"
  },
  {
      "id": "kit-automation",
      "name": "Kit",
      "description": "The go-to marketing hub for creators that helps you grow and monetize your audience with ease.",
      "category": "Email Automation",
      "url": "https://kit.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "kit.com",
      "brandColor": "#FF5C5C"
  },
  {
      "id": "mailerlite-automation",
      "name": "MailerLite",
      "description": "Create advanced email marketing campaigns with features like automation, landing pages, and surveys.",
      "category": "Email Automation",
      "url": "https://mailerlite.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "mailerlite.com",
      "brandColor": "#00A235"
  },

  // WhatsApp Automation
  {
      "id": "wati-automation",
      "name": "WATI",
      "description": "WhatsApp Business API platform built for customer support, marketing, and sales.",
      "category": "WhatsApp Automation",
      "url": "https://wati.io",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Paid",
      "rating": 4.6,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "wati.io",
      "brandColor": "#00E676"
  },
  {
      "id": "aisensy-automation",
      "name": "AiSensy",
      "description": "Complete WhatsApp Marketing platform built on Official WhatsApp Business API.",
      "category": "WhatsApp Automation",
      "url": "https://aisensy.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Paid",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "aisensy.com",
      "brandColor": "#1A73E8"
  },
  {
      "id": "interakt-automation",
      "name": "Interakt",
      "description": "WhatsApp Business API solution for SMBs. Best for e-commerce, retail and D2C brands.",
      "category": "WhatsApp Automation",
      "url": "https://interakt.ai",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Paid",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "interakt.ai",
      "brandColor": "#FF5252"
  },
  {
      "id": "gallabox-automation",
      "name": "Gallabox",
      "description": "Conversational commerce platform for WhatsApp, helping businesses sell better.",
      "category": "WhatsApp Automation",
      "url": "https://gallabox.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Paid",
      "rating": 4.6,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "gallabox.com",
      "brandColor": "#00B0FF"
  },
  {
      "id": "zoko-automation",
      "name": "Zoko",
      "description": "Central hub for all your WhatsApp communication. Great for scaling sales and support.",
      "category": "WhatsApp Automation",
      "url": "https://zoko.io",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Paid",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "zoko.io",
      "brandColor": "#00C853"
  },

  // Lead Generation Automation
  {
      "id": "apollo-automation",
      "name": "Apollo",
      "description": "Sales intelligence and engagement platform to find buyers, connect, and close.",
      "category": "Lead Generation Automation",
      "url": "https://apollo.io",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.8,
      "featured": true,
      "dateAdded": new Date().toISOString(),
      "domain": "apollo.io",
      "brandColor": "#FFD600"
  },
  {
      "id": "clay-automation",
      "name": "Clay",
      "description": "Automate data enrichment, personalize outreach, and build automated lead generation workflows.",
      "category": "Lead Generation Automation",
      "url": "https://clay.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.9,
      "featured": true,
      "dateAdded": new Date().toISOString(),
      "domain": "clay.com",
      "brandColor": "#333333"
  },
  {
      "id": "phantombuster-automation",
      "name": "Phantombuster",
      "description": "Automate any action on LinkedIn, Twitter, Instagram, Google Maps, and more to generate leads.",
      "category": "Lead Generation Automation",
      "url": "https://phantombuster.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Paid",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "phantombuster.com",
      "brandColor": "#4C2BDB"
  },
  {
      "id": "lemlist-automation",
      "name": "Lemlist",
      "description": "Advanced cold email software for lead generation. Personalize cold emails & automate follow-ups.",
      "category": "Lead Generation Automation",
      "url": "https://lemlist.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Paid",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "lemlist.com",
      "brandColor": "#F92C5B"
  },
  {
      "id": "dripify-automation",
      "name": "Dripify",
      "description": "Advanced LinkedIn automation tool for lead generation. Build sales funnels and close more deals.",
      "category": "Lead Generation Automation",
      "url": "https://dripify.io",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Paid",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "dripify.io",
      "brandColor": "#185ABC"
  },

  // CRM Automation
  {
      "id": "hubspot-automation",
      "name": "HubSpot",
      "description": "Inbound marketing, sales, and service software. Automate your entire customer journey.",
      "category": "CRM Automation",
      "url": "https://hubspot.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.8,
      "featured": true,
      "dateAdded": new Date().toISOString(),
      "domain": "hubspot.com",
      "brandColor": "#FF7A59"
  },
  {
      "id": "zoho-crm-automation",
      "name": "Zoho CRM",
      "description": "Top-rated sales CRM software by customers globally. Automate tasks and close deals faster.",
      "category": "CRM Automation",
      "url": "https://zoho.com/crm",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "zoho.com",
      "brandColor": "#F0483E"
  },
  {
      "id": "pipedrive-automation",
      "name": "Pipedrive",
      "description": "Sales CRM & pipeline management software. Designed by salespeople for salespeople.",
      "category": "CRM Automation",
      "url": "https://pipedrive.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Paid",
      "rating": 4.6,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "pipedrive.com",
      "brandColor": "#00A15D"
  },
  {
      "id": "freshsales-automation",
      "name": "Freshsales",
      "description": "Sales CRM with built-in phone and email. Automate sales processes and find the right leads.",
      "category": "CRM Automation",
      "url": "https://freshworks.com/freshsales-crm",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.6,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "freshworks.com",
      "brandColor": "#02B875"
  },
  {
      "id": "salesforce-automation",
      "name": "Salesforce",
      "description": "The world’s #1 customer relationship management (CRM) platform. Advanced enterprise automation.",
      "category": "CRM Automation",
      "url": "https://salesforce.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Paid",
      "rating": 4.7,
      "featured": true,
      "dateAdded": new Date().toISOString(),
      "domain": "salesforce.com",
      "brandColor": "#00A1E0"
  },

  // Productivity Automation
  {
      "id": "calendly-automation",
      "name": "Calendly",
      "description": "Automated scheduling software to simplify booking appointments, interviews, and meetings.",
      "category": "Productivity Automation",
      "url": "https://calendly.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.8,
      "featured": true,
      "dateAdded": new Date().toISOString(),
      "domain": "calendly.com",
      "brandColor": "#006BFF"
  },
  {
      "id": "motion-automation",
      "name": "Motion",
      "description": "AI-powered calendar and project manager. Automatically plans your day and builds your schedule.",
      "category": "Productivity Automation",
      "url": "https://usemotion.com",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Paid",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "usemotion.com",
      "brandColor": "#000000"
  },
  {
      "id": "reclaim-ai-automation",
      "name": "Reclaim AI",
      "description": "Smart calendar assistant that automatically blocks time for tasks, routines, and breaks.",
      "category": "Productivity Automation",
      "url": "https://reclaim.ai",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "reclaim.ai",
      "brandColor": "#E24A4A"
  },
  {
      "id": "fireflies-ai-automation",
      "name": "Fireflies AI",
      "description": "AI meeting assistant that transcribes, summarizes, and analyzes your voice conversations.",
      "category": "Productivity Automation",
      "url": "https://fireflies.ai",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.7,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "fireflies.ai",
      "brandColor": "#FF3366"
  },
  {
      "id": "otter-ai-automation",
      "name": "Otter AI",
      "description": "Automated meeting notes. Records audio, writes notes, captures slides, and generates summaries.",
      "category": "Productivity Automation",
      "url": "https://otter.ai",
      "imageUrl": "https://images.unsplash.com/photo-1682687220199-d0124f48f95b?auto=format&fit=crop&q=80&w=800",
      "pricing": "Freemium",
      "rating": 4.8,
      "featured": false,
      "dateAdded": new Date().toISOString(),
      "domain": "otter.ai",
      "brandColor": "#2196F3"
  }
];

if (!content.includes('"manychat-automation"')) {
  const replacement = 'export const MOCK_TOOLS: Tool[] = [\n' + newTools.map(t => JSON.stringify(t, null, 4)).join(',\n') + ',';
  content = content.replace('export const MOCK_TOOLS: Tool[] = [', replacement);
  fs.writeFileSync(filePath, content);
  console.log('Added new tools with -automation suffix');
} else {
  console.log('Tools already added');
}
